version: '3.8'
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  dependency-check:
    image: owasp/dependency-check
    environment:
      - NVD_MIRROR=https://mirror.nvd.nist.gov
      - DATA_DIRECTORY=/usr/share/dependency-check/data
    volumes:
      - dependency_data:/usr/share/dependency-check/data
      - ./:/src
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "mkdir -p /src/reports/dependency-check &&
      /usr/share/dependency-check/bin/dependency-check.sh
      --scan /src
      --format 'HTML'
      --format 'JSON'
      --out '/src/reports/dependency-check/dependency-check-report'
      --log '/src/reports/dependency-check/dependency-check.log'
      --noupdate
      --project '${JOB_NAME}'"
    working_dir: /src

  trivy:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - trivy_cache:/root/.cache/trivy

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
  dependency_data:
  trivy_cache: