name: Sync to GitLab

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 전체 히스토리를 가져오기 위해 추가

    - name: Set up Git
      run: |
        git config user.name "okhi3945"
        git config user.email "yhoka@naver.com"

    - name: Add GitLab remote repository
      # 자체 호스팅 GitLab URL 사용
      run: git remote add gitlab http://oauth2:${GITLAB_TOKEN}@myregistry.com:80/root/lowcostchillguygitlab.git
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    - name: Push to GitLab
      run: git push gitlab main
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}