name: Sync to GitLab

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 전체 히스토리를 가져오기 위해 추가

    - name: Set up Git
      run: |
        git config user.name "okhi3945"
        git config user.email "yhoka@naver.com"

    - name: Add GitLab remote repository
      # GitLab URL 형식 수정
      run: git remote add gitlab https://gitlab.com/${{ secrets.GITLAB_USERNAME }}/${{ secrets.GITLAB_REPO_NAME }}.git

    - name: Push to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: git push "https://oauth2:${GITLAB_TOKEN}@gitlab.com/${{ secrets.GITLAB_USERNAME }}/${{ secrets.GITLAB_REPO_NAME }}.git" main